config/routes.rb
Rails.application.routes.draw do
  root :to => 'charges#index'
  resources :charges, only: [:index]
  resources :customers, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :customer

  validates_presence_of :amount, :currency, :customer_id

  scope :successful, -> { where(paid: true).where(refunded: false) }
  scope :disputed, -> { where(paid: true).where(refunded: true) }
  scope :failed, -> { where(paid: false) }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :charges

  validates_presence_of :first_name, :last_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @successful = Charge.successful
    @disputed = Charge.disputed
    @failed = Charge.failed
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def charge_params
      params.require(:charge).permit(:paid, :currency, :amount, :refunded, :customer)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def in_dollar(cent)
    return "$#{cent/100}.#{cent%100}" unless cent.zero?
    return 0
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/charges/_form.html.erb
<%= form_with(model: charge, local: true) do |form| %>
  <% if charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :refunded %>
    <%= form.check_box :refunded %>
  </div>

  <div class="field">
    <%= form.label :customer %>
    <%= form.text_field :customer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/_records.html.erb
<h1><%= title %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody class="charges-<%=title%>" style="background-color: <%= bg_color %>">
    <% unless charges.blank? %>
      <% charges.each do |charge| %>
        <tr>
          <td><%= charge.customer.full_name %></td>
          <td><%= in_dollar(charge.amount) %></td>
          <td><%= charge.updated_at.strftime('%Y/%m/%d') %></td>
        </tr>
      <% end %>
    <% end %> 
  </tbody>
</table>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<%= render 'records', charges: @failed, title: 'Failed', bg_color: '#FF0000' %>
<%= render 'records', charges: @disputed, title: 'Disputed', bg_color: '#FF5400' %>
<%= render 'records', charges: @successful, title: 'Successful', bg_color: '' %>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paid:</strong>
  <%= @charge.paid %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @charge.currency %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @charge.amount %>
</p>

<p>
  <strong>Refunded:</strong>
  <%= @charge.refunded %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @charge.customer %>
</p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnpingSmTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>